apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redpanda-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-redpanda-console
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-redpanda-console
  type: {{ .Values.service.type }}