apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: default
type: Opaque
data:
  sql_alchemy_conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3c6YWlyZmxvd0BkYXRhLWxha2UtcG9zdGdyZXM6NTQzMi9haXJmbG93  # postgresql+psycopg2://airflow:airflow@data-lake-postgres:5432/airflow
  fernet_key: UV92a1NPd0RvQUNxUDF1SDhIOTI2WDhrUnVFTXM4SWdEUlhyVVJkMWVQND0K
  secret_key: Z1loUmpYMVR0UkdsdkZWeFg4ZHVJMFBQcjNaTkhWakU4UHY2UDBvdlp5WQ==