---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: airflow-sa
  namespace: default
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io