apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-airflow
spec:
  selector:
    app: {{ .Release.Name }}-airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
