FROM apache/airflow:2.7.1
USER root

RUN apt-get update && apt-get install -y curl tar gzip && \
    curl -L -o /tmp/jdk8.tar.gz https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u412-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u412b08.tar.gz && \
    mkdir -p /opt/java/openjdk8 && \
    tar -xzf /tmp/jdk8.tar.gz -C /opt/java/openjdk8 --strip-components=1 && \
    rm /tmp/jdk8.tar.gz && \
    update-alternatives --install /usr/bin/java java /opt/java/openjdk8/bin/java 1 && \
    update-alternatives --install /usr/bin/javac javac /opt/java/openjdk8/bin/javac 1

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Cài đặt Spark
RUN curl -L https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz | tar xz -C /opt/ \
    && mv /opt/spark-3.5.1-bin-hadoop3 /opt/spark \
    && chown -R airflow:root /opt/spark

USER airflow

# Cài đặt các Python package
RUN pip install --no-cache-dir \
    "minio==7.1.15" "kafka-python==2.0.2" "apache-airflow-providers-openlineage==1.8.0" \
    "pandas==2.0.0" "pyarrow==10.0.1" "retry==0.9.2" "urllib3==1.26.18" \
    "thrift==0.16.0"
RUN mkdir -p /opt/spark/jars \
    && curl -L https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar -o /opt/spark/jars/postgresql-42.7.3.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar -o /opt/spark/jars/hadoop-aws-3.3.4.jar \
    && curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.761/aws-java-sdk-bundle-1.12.761.jar -o /opt/spark/jars/aws-java-sdk-bundle-1.12.761.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.6/hadoop-common-3.3.6.jar -o /opt/spark/jars/hadoop-common-3.3.6.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.3.6/hadoop-hdfs-3.3.6.jar -o /opt/spark/jars/hadoop-hdfs-3.3.6.jar \
    && curl -L https://repo1.maven.org/maven2/commons-logging/commons-logging/1.3.4/commons-logging-1.3.4.jar -o /opt/spark/jars/commons-logging-1.3.4.jar \
    && curl -L https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar -o /opt/spark/jars/slf4j-api-1.7.36.jar \
    && curl -L https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar -o /opt/spark/jars/log4j-1.2.17.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar -o /opt/spark/jars/httpcore-4.4.16.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar -o /opt/spark/jars/httpclient-4.5.14.jar \
    && curl -L https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core-4.2.26/metrics-core-4.2.26.jar -o /opt/spark/jars/metrics-core-4.2.26.jar \
    && curl -L https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1.jar -o /opt/spark/jars/commons-codec-1.17.1.jar \
    && curl -L https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.jar -o /opt/spark/jars/javax.servlet-api-4.0.1.jar \
    && curl -L https://repo1.maven.org/maven2/joda-time/joda-time/2.12.7/joda-time-2.12.7.jar -o /opt/spark/jars/joda-time-2.12.7.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/calcite/calcite-core/1.26.0/calcite-core-1.26.0.jar -o /opt/spark/jars/calcite-core-1.26.0.jar \
    && curl -L https://repo1.maven.org/maven2/org/datanucleus/datanucleus-rdbms/5.2.4/datanucleus-rdbms-5.2.4.jar -o /opt/spark/jars/datanucleus-rdbms-5.2.4.jar \
    && curl -L https://repo1.maven.org/maven2/org/datanucleus/datanucleus-core/5.2.4/datanucleus-core-5.2.4.jar -o /opt/spark/jars/datanucleus-core-5.2.4.jar \
    && curl -L https://repo1.maven.org/maven2/org/datanucleus/datanucleus-api-jdo/5.2.4/datanucleus-api-jdo-5.2.4.jar -o /opt/spark/jars/datanucleus-api-jdo-5.2.4.jar \
    && curl -L https://repo1.maven.org/maven2/com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.jar -o /opt/spark/jars/HikariCP-5.0.1.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.5/spark-sql-kafka-0-10_2.12-3.5.5.jar -o /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.5.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/spark/spark-streaming-kafka-0-10_2.12/3.5.5/spark-streaming-kafka-0-10_2.12-3.5.5.jar -o /opt/spark/jars/spark-streaming-kafka-0-10_2.12-3.5.5.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.5/spark-token-provider-kafka-0-10_2.12-3.5.5.jar -o /opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.5.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar -o /opt/spark/jars/kafka-clients-3.4.1.jar \
    && curl -L https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar -o /opt/spark/jars/jsr305-3.0.0.jar \
    && curl -L https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar -o /opt/spark/jars/commons-pool2-2.11.1.jar \
    && curl -L https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar -o /opt/spark/jars/lz4-java-1.8.0.jar \
    && curl -L https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.5/snappy-java-1.1.10.5.jar -o /opt/spark/jars/snappy-java-1.1.10.5.jar
USER root
RUN curl -L https://archive.apache.org/dist/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz | tar xz -C /tmp && \
    cp /tmp/apache-hive-3.1.3-bin/lib/*.jar /opt/spark/jars/ && \
    rm -rf /tmp/apache-hive-3.1.3-bin apache-hive-3.1.3-bin.tar.gz
RUN find /opt/spark/jars -name 'hive-*.jar' ! -name 'hive-*-3.1.3.jar' -delete && \
    find /opt/spark/jars -name 'datanucleus-*.jar' ! -name 'datanucleus-*-5.2.4.jar' -delete && \
    find /opt/spark/jars -name 'HikariCP-*.jar' ! -name 'HikariCP-5.0.1.jar' -delete && \
    rm -f /opt/spark/jars/derby-*.jar
USER airflow
COPY weather_processor.py .