FROM trinodb/trino:474

# Tạo thư mục cho plugin hive
RUN mkdir -p /usr/lib/trino/plugin/hive

# Tải hadoop-aws-3.3.4.jar từ Maven Central
RUN curl -L -o /usr/lib/trino/plugin/hive/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar

# Tải aws-java-sdk-bundle-1.12.261.jar từ Maven Central
RUN curl -L -o /usr/lib/trino/plugin/hive/aws-java-sdk-bundle-1.12.261.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.261/aws-java-sdk-bundle-1.12.261.jar