image:
  repository: docker.redpanda.com/redpandadata/console
  tag: latest
  pullPolicy: IfNotPresent
console:
  config:
    kafka:
      brokers:
        - data-lake-kafka.default.svc.cluster.local:9092
      sasl:
        enabled: false
    tls:
      enabled: false
service:
  type: NodePort
  port: 8080
  nodePort: 30080
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi