apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-spark-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.spark.ingress.className }}
  rules:
  - host: {{ .Values.spark.ingress.hosts.spark }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-spark-master
            port:
              number: 8081