apiVersion: v2
name: data-lake-project
description: Umbrella Helm Chart for Data Lake
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: redis
    version: 0.1.0
    repository: file://charts/redis
  - name: minio
    version: 0.1.0
    repository: "file://charts/minio"
  - name: hive
    version: 0.1.0
    repository: "file://charts/hive"
  - name: trino
    version: 0.1.0
    repository: "file://charts/trino"
  - name: superset
    version: 0.1.0
    repository: "file://charts/superset"
  - name: spark
    version: 0.1.0
    repository: "file://charts/spark"
  - name: kafka
    version: 0.1.0
    repository: "file://charts/kafka"
  - name: airflow
    version: 0.1.0
    repository: "file://charts/airflow"
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
  - name: redpanda-console
    version: 0.1.0
    repository: file://charts/redpanda-console
    condition: redpanda-console.enabled
